### ISSUE TITLE
prime-select requires nvidia-libglx.so but it doesn't exist

### ISSUE THREAD

**Issue by Rush** [openSUSE/SUSEPrime#29]
My laptop crashed during installation of NVIDIA packages and I had to force reinstall them ...

Unfortunately now `prime-select` doesn't work for me. It seems that it's trying to `update-alternatives` of `libglx.so` to `/usr/lib64/xorg/modules/extensions/nvidia/nvidia-libglx.so`.

https://github.com/openSUSE/SUSEPrime/blob/master/prime-select.sh#L176

But on my laptop "/usr/lib64/xorg/modules/extensions/nvidia/nvidia-libglx.so" does not exist. Any idea how to get `/usr/lib64/xorg/modules/extensions/nvidia/nvidia-libglx.so`? Which package installs it?

**Comment by sndirsch** [comment]
update-alternatives for glx Xserver extension is no longer necessary with 435.21 drivers. Xorg's libglx.so and NVIDIA's glx library are now loaded in parallel (the latter one by NVIDIA's X driver). You can ignore the error message.

x11-video-nvidiaG05.changes
-------------------------------------------------------------------
Mon Sep  9 13:13:27 UTC 2019 - Stefan Dirsch <sndirsch@suse.com>

- get rid of update-alternatives for NVIDIA's GLX extension; no
  longer needed since 410.xx (boo#1149858)

**Comment by sndirsch** [comment]
Closing ...
