### ISSUE TITLE
SUSEPrime empty

### ISSUE THREAD

**Issue by DevDorrejo** [openSUSE/SUSEPrime#39]
hello,

the package SUSEPrime after install from the repos the folder is practically empty compare to the git repo.

![image](https://user-images.githubusercontent.com/7697566/68688939-04869580-0546-11ea-8ec3-a8fc97306125.png)

so where can i find the files, because i am using G5, and when i switch to the intel bbswitch isnt turning off the nvidia.

thank you.

**Comment by simopil** [comment]
The executable is located in /usr/sbin/prime-select
What about your log?

**Comment by sndirsch** [comment]
@DevDorrejo Looks like you're talking about our suse-prime/suse-prime-bbswitch packages from obs://X11:XOrg project or Tumbleweed. First make sure that you have installed suse-prime-bbswitch package instead of suse-prime package. Then running "prime-select intel" should be enough. Probably you need a reboot afterwards though. Not sure which files in addition you expect in /etc/prime ... maybe you're looking for the modprobe/dracut/udev config files.

# rpm -qpl suse-prime-0.7.2-56.2.noarch.rpm |grep -e rules -e dracut -e modprobe
/etc/modprobe.d/09-nvidia-modprobe-pm-G05.conf
/usr/lib/dracut/dracut.conf.d/90-nvidia-dracut-G05.conf
/usr/lib/udev/rules.d/90-nvidia-udev-pm-G05.rules

# rpm -qpl suse-prime-bbswitch-0.7.2-56.2.noarch.rpm |grep -e rules -e dracut -e modprobe
/etc/modprobe.d/09-nvidia-modprobe-bbswitch-G04.conf

dracut and udev config files are not needed for bbswitch package.

**Comment by DevDorrejo** [comment]
ok thank you, some tips how to use the new nvidia mode for the last change that you mention?

**Comment by sndirsch** [comment]
> ok thank you, some tips how to use the new nvidia mode for the last change that you mention?

I don't understand what you mean with new nvidia mode for my last change you believe I was mentioning.

**Comment by DevDorrejo** [comment]
https://github.com/openSUSE/SUSEPrime#nvidia-power-off-support-with-435xxx-driver-g05-driver-packages

i am talking about this, without the need of bbswitch

**Comment by sndirsch** [comment]
@DevDorrejo This section is not needed when using the suse-prime package instead of git. Not sure what's missing in the package and what's the remaining issue after all. :-(

**Comment by DevDorrejo** [comment]
ok, and how i can use that power off from the 435xxx if i installed from the package?

**Comment by sndirsch** [comment]
@DevDorrejo Everything should already be set once the package is installed. But the feature requires a Turing or newer GPU, which currently means GeForce GTX 16XX, GeForce RTX 20XX or Quadro RTX 4000/5000/6000/8000. More details you can find in NVIDIA's README.txt Chapter 22.

**Comment by sndirsch** [comment]
> @DevDorrejo Everything should already be set once the package is installed. But the feature requires a Turing or newer GPU, which currently means GeForce GTX 16XX, GeForce RTX 20XX or Quadro RTX 4000/5000/6000/8000. More details you can find in NVIDIA's README.txt Chapter 22.

firefox /usr/share/doc/packages/x11-video-nvidiaG05/html/dynamicpowermanagement.html

**Comment by DevDorrejo** [comment]
Ok, thank you, the post can be closed

**Comment by sndirsch** [comment]
Ok. I hope I could help you in the end.
