### ISSUE TITLE
[Question] Clarification on AllowNVIDIAGPUScreens and bbswitch

### ISSUE THREAD

**Issue by Nabawe** [openSUSE/SUSEPrime#54]
Hi sorry to bother in the README.md > Installation/usage says:

> 3. On intel configurations, powering off the NVIDIA card with bbswitch (since 390.xxx driver) or DynamicPowerManagement option (since 435.xx driver and Turing GPU or later) to save power and decrease temperature is supported but requires additional manual setup. Refer to instructions below.

> 4. Since 435.xx driver you can make use of NVIDIA's PRIME Render Offload feature in intel configurations (Xserver of Leap 15.2 or later needed!). Option "AllowNVIDIAGPUScreens" is already taken care of by intel X configs. You only need to set the __NV* environment variables. Check https://download.nvidia.com/XFree86/Linux-x86_64/435.21/README/primerenderoffload.html for more details.

I'm on a ASUS N56V i5 with an optimus setup running Tumbleweed and a GEFORCE 740M dGPU.

When I am about configuring SUSE Prime as told in:
https://en.opensuse.org/SDB:NVIDIA_SUSE_Prime

I get directed to this GitHub page and after reading this and several other pages I'm unsure if I actually need bbswitch to complete the setup.
The AllowNVIDIAGPUScreens are already in the /etc/prime config files by default.

Everything was automatically set up by following the instructions on:
https://en.opensuse.org/SDB:NVIDIA_drivers

If I run:
` # glxinfo | grep 'OpenGL renderer'`
I get:
`string: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)`

If:
`prime-select get-current`
Then:
`Driver configured: undefined`
I suspect this is coz I haven't issued prime-select nvidia yet.

Which instructions or steps should I follow to finish?.

Thanks A LOT for your time and effort.

**Comment by sndirsch** [comment]
Thanks for the feedback! Just improved the documentation in the README.md (abstract 3 in your snippet). Your NVIDIA GPU is too old in order to use the powersave option in intel/nvidia mode. It's *not* a Turing GPU! You need to decide. Either use no powersave mode for NVIDIA GPU, but use its render capabilities (prime-select nvidia). Or don't use NVIDIA GPU at all, but turn it off completely using bbswitch (prime-select intel). Check README.md for more details on the latter option.

**Comment by sndirsch** [comment]
Closing ...
